name: Run Go App

on:
  schedule:
    - cron: "0 6 * * *"
  # Run the workflow when a push event of items_for_scrape.json is triggered on the master branch
  push:
    branches:
      - master
    paths:
      - items_for_scrape.json

  workflow_dispatch:

jobs:
  run-go-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download previous price data
        uses: actions/download-artifact@v4
        with:
          name: prices-file
          path: ./prices.json
        continue-on-error: true

      - name: Check if prices.json error is because it doesn't exist
        run: |
          if [ -f ./prices.json ]; then
            echo "prices.json exists. Exiting workflow."
            exit 1 
          else
            echo "prices.json does not exist, creating a new one."
            echo '{}' > ./prices.json
          fi

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"

      - name: Run Go application
        run: go run .

      - name: Upload new price data
        uses: actions/upload-artifact@v4
        with:
          name: prices-file
          path: ./prices.json

      - name: Send email with prices.json attachment
        run: |
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            --header 'Content-Type: application/json' \
            --data '{
              "personalizations": [
                {
                  "to": [
                    {
                      "email": "${{ secrets.SENDGRID_TO_EMAIL }}"
                    }
                  ],
                  "subject": "Scraped Latest Price Data"
                }
              ],
              "from": {
                "email": "${{ secrets.SENDGRID_FROM_EMAIL }}"
              },
              "content": [
                {
                  "type": "text/plain",
                  "value": "Attached is the latest prices.json file."
                }
              ],
              "attachments": [
                {
                  "content": "'$(base64 ./prices.json)'",
                  "filename": "prices.json",
                  "type": "application/json",
                  "disposition": "attachment"
                }
              ]
            }'