name: Run Go App

on:
  schedule:
    - cron: "0 6 * * *"
  # Run the workflow when a push event of items_for_scrape.json is triggered on the master branch
  push:
    branches:
      - master
    paths:
      - items_for_scrape.json

  workflow_dispatch:

jobs:
  run-go-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO -> download the artifact whose id is saved in a variable (secret)
      # - name: Download previous price data
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: prices-file
      #     path: ./prices.json
      #   continue-on-error: true

      # TODO -> remove once the above step is implemented
      - name: Create empty prices.json file
        run: |
            echo "creating prices.json file"
            echo '{}' > ./prices.json

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"

      - name: Run Go application
        run: go run .

      # TODO -> can you save artifact id in a variable (secret) and use it in the next workflow
      # - name: Upload new price data
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: prices-file
      #     path: ./prices.json

      - name: Send email with prices.json attachment
        continue-on-error: true
        run: |
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            --header 'Content-Type: application/json' \
            --data '{
              "personalizations": [
                {
                  "to": [
                    {
                      "email": "${{ secrets.SENDGRID_TO_EMAIL }}"
                    }
                  ],
                  "subject": "Scraped Latest Price Data"
                }
              ],
              "from": {
                "email": "${{ secrets.SENDGRID_FROM_EMAIL }}"
              },
              "content": [
                {
                  "type": "text/plain",
                  "value": "'$(jq ./prices.json)'"
                }
              ],
            }'

      - name: Send email with prices.json attachment
        continue-on-error: true
        run: |
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            --header 'Content-Type: application/json' \
            --data '{
              "personalizations": [
                {
                  "to": [
                    {
                      "email": "${{ secrets.SENDGRID_TO_EMAIL }}"
                    }
                  ],
                  "subject": "Scraped Latest Price Data"
                }
              ],
              "from": {
                "email": "${{ secrets.SENDGRID_FROM_EMAIL }}"
              },
              "content": [
                {
                  "type": "application/json",
                  "value": "'$(jq ./prices.json)'"
                }
              ],
            }'