name: Run Go App

on:
  # Run the workflow every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Run the workflow when a push event is triggered
  push:
    branches:
      - master
    paths:
      - items_for_scrape.json

  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  run-go-app:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # Use the Go version you need

      # Run the Go application
      - name: Run Go application
        run: go run .